language: python
python:
  - "3.6"

services:
  - postgresql

env:
  - DATABASE_URI=postgres://postgres:@localhost:5432/postgres

before_script:
  - psql -c 'create database testdb;' -U postgres

# command to install dependencies
install: "pip3 install -r requirements.txt"

# command to run tests
script: nosetests

after_success:
  - bash <(curl -s https://codecov.io/bash)
